### ISSUE TITLE
Persistent workspace session shows "Unknown State"

### ISSUE THREAD

**Issue by MartinLindenmaierSBB** [DSD-DBS/capella-collab-manager#127] opened 2022-07-18 08:38 UTC
After a certain/unpredictable amount of time, the persistent workspace session shows "Unknown State" although the capella workspace session is still open and usable in another tab. 

There is no way to reconnect after closing the browser and the session needs to be terminated and a new one has to be created.

![image](https://user-images.githubusercontent.com/63055539/179474402-6aacf0bb-19be-4f53-9017-0cf824f0a813.png)

**Comment by MoritzWeber0** [comment] 2022-07-22 09:35
Hi @MartinLindenmaierSBB, thanks you for creating the issue. The issue is already tracked by #75. I'll close this issue as duplicate.

**Closed by MoritzWeber0** 2022-07-22 09:35 UTC
