### ISSUE TITLE
Issues with Description edit

### ISSUE THREAD

**Issue by SergioGuindasGarciaDB** [DSD-DBS/capella-collab-manager#199] opened 2022-08-25 08:42 UTC
I am able to modify any property of any object in the model (Capabilities, functions, actors,...) except their description.

I encounter the problem every time I try to edit a description, it was not a single time event

**Comment by MoritzWeber0** [comment] 2022-08-26 13:37
Hi @SergioGuindasGarciaDB - thanks for reporting the bug. Could you confirm that the description editor is displayed but the save button doesn't work? 

We have already reported the issue to the Capella development team, you can find more information here:: https://github.com/eclipse/capella/issues/2316

**Comment by SergioGuindasGarciaDB** [comment] 2022-08-26 13:39
Exactly, the  editor is correctly displayed but it is not possible to save the modification.

**Comment by MoritzWeber0** [comment] 2022-08-26 13:45
As a workaround, you can try to use <kbd>CTRL</kbd>+<kbd>S</kbd> on your keyboard. 

However, since the issue is already tracked in the Capella repository, I'll close this issue.

**Closed by MoritzWeber0** 2022-08-26 13:45 UTC

**Comment by SergioGuindasGarciaDB** [comment] 2022-10-11 08:43
Hi,

I have additional problem with the description editor other than saving. Quite often I get the following error, usually when trying to add an hyperlink:

***@***.***

Shall I create an independent issue?
